import comment,comment_length,currency,datetimeorder,direction,duration,idgenerate,magicnum,size,statusgenerate,tag,tag_length,typegenerate,generateinsertrequest

idgenerate.generate_save_id()
size.generate_size()
magicnum.generate_magic_num()
typegenerate.gener_type()
direction.generate_direction()
tag.generate_tag()
datetimeorder.date_time()
tag_length.generate_tag_length()
comment.generate_comment()
comment_length.generate_comment_length()
currency.generate_currency()
duration.generate_duration()
generateinsertrequest.generate_request()
statusgenerate.status_gen()
