import idgenerate,size,magicnum,typegenerate,direction,tag,tag_length,comment,comment_length,duration,currency,datetimeorder,statusgenerate

idgenerate.generate_save_id()
size.generate_size()
magicnum.generate_magic_num()
typegenerate.gener_type()
direction.generate_direction()
tag.generate_tag()
comment.generate_comment()
comment_length.generate_comment_length()
tag_length.generate_tag_length()
duration.generate_duration()
currency.generate_currency()
datetimeorder.date_time()
statusgenerate.status_gen()
